import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter, Roboto_Flex } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Footer from "@/components/Footer";
import Banner from "@/components/Banner";
import Filter from "@/components/Filter";
import Navigation from "@/components/Navigation";
import Presentation from "@/components/Presentation";
import Articles from "@/components/Articles";
import { db } from "../firebase-config";
import { collection, getDocs, doc, onSnapshot } from "firebase/firestore";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    //loadData();
    return () => {};
  }, []);

  const loadData = async () => {
    const databaseProducts = collection(db, "products");
    const data = await getDocs(databaseProducts);
    const products = data.docs.map((doc) => doc.data());
    console.log({ products });
    setProducts(products);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Banner />
        <Navigation />
        <Presentation /> */}
        {/* <Filter /> */}
        <Articles style={{ flex: 1 }} products={products} />
        {/* <Footer /> */}
      </main>
    </>
  );
}
